name: "wine_prediction_model"
platform: "pytorch_libtorch"
input [
  {
    name: "wine_data__0"
    data_type: TYPE_FP32
    dims: [ -1, 77 ]
  },
  {
    name: "climate_data__1"
    data_type: TYPE_FP32
    dims: [ -1, 7, 22 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 1 ]  
  }
]
